export const satSchedule = [
  {
    zone: "Богема",
    section: "Hype",
    color: "#e63946",
    lection: [
      {
        start: "12:00",
        end: "12:50",
        name: "Открытие",
        desc: null,
        tag: null,
        speaker: [
          { name: "Кирилл Мокевнин", desc: "Founder Hexlet" },
          { name: "Андрей Смирнов", desc: "CTO Magnit Tech" },
          { name: "Анна Афонина", desc: "Founder ProIT Fest" },
        ],
        zone: "Богема",
        section: "Hype",
      },
      {
        start: "13:00",
        end: "13:50",
        name: "Как сделать проект понятным для AI-агентов",
        desc: null,
        tag: null,
        speaker: [{ name: "Кирилл Мокевнин", desc: "Founder Hexlet" }],
        zone: "Богема",
        section: "Hype",
      },
      {
        start: "15:00",
        end: "15:50",
        name: "Weekend в IT",
        desc: "живая запись подкаста",
        tag: null,
        speaker: [
          { name: "Степан Минин", desc: "Разработчик Золотое Яблоко" },
          {
            name: "Александр Макаров",
            desc: "CTO Twindo.ai | Yii framework lead | PHP Russia",
          },
        ],
        zone: "Богема",
        section: "Hype",
      },
      {
        start: "16:00",
        end: "16:50",
        name: "Зумер vs Ветеран IT",
        desc: null,
        tag: null,
        speaker: [
          { name: "Константин Пантелеев", desc: "партнер kosta.capital" },
          {
            name: "Анастасия Волконская",
            desc: "Руководитель комитета по инвестициям РУССОФТ",
          },
          { name: "Валентин Микляев", desc: "серийный предприниматель" },
        ],
        zone: "Богема",
        section: "Hype",
      },
      {
        start: "17:00",
        end: "17:50",
        name: "#Безвотэтоговотвсего. Управленческие дилеммы",
        desc: "что делать, когда все варианты плохие",
        tag: null,
        speaker: [
          {
            name: "Елена Бессонова",
            desc: "модератор, ex. Head of DevRel SberHealth",
          },
          { name: "Дмитрий Безуглый", desc: "Founder Master-Strategy" },
          { name: "Василий Гигаури", desc: "СТО Честный знак" },
        ],
        zone: "Богема",
        section: "Hype",
      },
      {
        start: "19:00",
        end: "22:00",
        name: "FuckUp Night",
        desc: null,
        tag: null,
        speaker: [
          {
            name: "Степан Калашников",
            desc: "тренер по публичным выступлениям",
          },
        ],
        zone: "Богема",
        section: "Hype",
      },
    ],
  },
  {
    zone: "Монте Карло",
    section: "Hard AI",
    color: "#6a4c93",
    lection: [
      {
        start: "12:00",
        end: "12:50",
        name: "HADI на стероидах: проверяем продуктовые гипотезы с AI",
        desc: "Воркшоп",
        tag: "workshop",
        speaker: [{ name: "Георгий Мартиросов", desc: "CEO getaiaiai.ru" }],
        zone: "Монте Карло",
        section: "Hard AI",
      },
      {
        start: "13:00",
        end: "13:50",
        name: "Prompt to Production",
        desc: "Собираем генеративный пайплайн для фото и видео. Креатив как микросервис",
        tag: null,
        speaker: [
          {
            name: "Олеся Савельева",
            desc: "Президент Федерации спортивной программирования",
          },
        ],
        zone: "Монте Карло",
        section: "Hard AI",
      },
      {
        start: "15:00",
        end: "15:50",
        name: "Start Архитектурные Коты",
        desc: null,
        tag: null,
        speaker: null,
        zone: "Монте Карло",
        section: "Hard AI",
      },
      {
        start: "16:00",
        end: "16:50",
        name: "Квантовый скачок в ИТ с помощью AI",
        desc: null,
        tag: null,
        speaker: [
          {
            name: "Валерий Никаноров",
            desc: "Руководитель AI, Альфа-Инвестиции",
          },
          { name: "Анна Суходоева", desc: "ML-инженер, Альфа-Инвестиции" },
        ],
        zone: "Монте Карло",
        section: "Hard AI",
      },
      {
        start: "17:00",
        end: "17:50",
        name: "Формируем гайдлайн по выбору модели и экономии токенов",
        desc: null,
        tag: null,
        speaker: [
          {
            name: "Денис Ковшарев",
            desc: "Android-разработчик Яндекс.Вертикали",
          },
        ],
        zone: "Монте Карло",
        section: "Hard AI",
      },
      {
        start: "19:00",
        end: "22:00",
        name: "По пиву с Филом Ранжиным",
        desc: null,
        tag: "drinkup",
        speaker: [{ name: "Фил Ранжин", desc: null }],
        zone: "Монте Карло",
        section: "Hard AI",
      },
    ],
  },
  {
    zone: "Новый Орлеан",
    section: "Golang",
    color: "#00b4d8",
    lection: [
      {
        start: "12:00",
        end: "12:50",
        name: "SIMD в Go 1.26 с нуля",
        desc: "от API процессора до собственной библиотеки",
        tag: "workshop",
        speaker: [{ name: "Игорь Панасюк", desc: "TeamLead в Яндекс" }],
        zone: "Новый Орлеан",
        section: "Golang",
      },
      {
        start: "13:00",
        end: "13:50",
        name: "Охотимся на утечки горутин",
        desc: "Воркшоп",
        tag: "workshop",
        speaker: [{ name: "Арсений Самойлов", desc: "NDA" }],
        zone: "Новый Орлеан",
        section: "Golang",
      },
      {
        start: "15:00",
        end: "15:50",
        name: "Пишем AI-агента на Golang с Eino",
        desc: "Воркшоп",
        tag: "workshop",
        speaker: [{ name: "Станислав Иванкевич", desc: "Техлид в СберТех" }],
        zone: "Новый Орлеан",
        section: "Golang",
      },
      {
        start: "16:00",
        end: "16:50",
        name: "Easy way построения gRPC сервиса",
        desc: null,
        tag: null,
        speaker: [{ name: "Василий Близнецов", desc: "Founder EasyP" }],
        zone: "Новый Орлеан",
        section: "Golang",
      },
      {
        start: "17:00",
        end: "17:50",
        name: "LLM-судья на замену: поднимаем качество агента живую",
        desc: "Воркшоп",
        tag: "workshop",
        speaker: [
          {
            name: "Максим Зотеев",
            desc: "Разработчик мобильного приложения в Яндекс.Вертикали",
          },
        ],
        zone: "Новый Орлеан",
        section: "Golang",
      },
      {
        start: "19:00",
        end: "22:00",
        name: "StandUp: Антикризисный разговор",
        desc: null,
        tag: "standup",
        speaker: [
          {
            name: "Дмитрий Алин",
            desc: "Руководитель группы разработки, SPb PHP",
          },
        ],
        zone: "Новый Орлеан",
        section: "Golang",
      },
    ],
  },
  {
    zone: "Олимп",
    section: "Hard",
    color: "#264653",
    lection: [
      {
        start: "12:00",
        end: "12:50",
        name: "Мастер-класс по нефункциональным требованиям в Архитектуре",
        desc: null,
        tag: "workshop",
        speaker: [
          { name: "Филипп Дильгядо", desc: null },
          { name: "Даниил Подольский", desc: null },
        ],
        zone: "Олимп",
        section: "Hard",
      },
      {
        start: "13:00",
        end: "13:50",
        name: "Java: Компилируем формулы в рантайме во имя перфа",
        desc: null,
        tag: null,
        speaker: [
          {
            name: "Петр Портнов",
            desc: "Ведущий разработчик поисковой платформы Ozon",
          },
        ],
        zone: "Олимп",
        section: "Hard",
      },
      {
        start: "15:00",
        end: "15:50",
        name: "Твой идеальный java backend",
        desc: null,
        tag: null,
        speaker: [
          {
            name: "Михаил Поливаха",
            desc: "Java Developer, Spring Community Board, Axelix",
          },
        ],
        zone: "Олимп",
        section: "Hard",
      },
      {
        start: "16:00",
        end: "16:50",
        name: "Python: Оркестрация subagents: Coder → Reviewer → Summarizer",
        desc: "Воркшоп",
        tag: "workshop",
        speaker: [
          {
            name: "Алексей Жиряков",
            desc: "Исполнительный директор, платформа генеративного ИИ Сбер",
          },
        ],
        zone: "Олимп",
        section: "Hard",
      },
      {
        start: "17:00",
        end: "17:50",
        name: "Python: Пишем и публикуем opensource проект",
        desc: null,
        tag: null,
        speaker: [{ name: "Денис Аникин", desc: "Техлид Райффайзен Банк" }],
        zone: "Олимп",
        section: "Hard",
      },
      {
        start: "19:00",
        end: "22:00",
        name: "Игра: выживи в корпорате",
        desc: null,
        tag: "game",
        speaker: [{ name: "Андрей Кириллов", desc: "ТимЛид" }],
        zone: "Олимп",
        section: "Hard",
      },
    ],
  },
  {
    zone: "Barbie",
    section: "Women in tech",
    color: "#ffafcc",
    lection: [
      {
        start: "12:00",
        end: "12:50",
        name: "Практикум: Не самозванка",
        desc: "Реальные инструменты против синдрома",
        tag: "workshop",
        speaker: [
          {
            name: "Полина Рейнер",
            desc: "ведущая, Senior QA Engineer VK Tech",
          },
        ],
        zone: "Barbie",
        section: "Women in tech",
      },
      {
        start: "13:00",
        end: "13:50",
        name: "Говорить — не значит хвастаться",
        desc: "как расти в карьере через навык уверенно говорить о своих достижениях",
        tag: null,
        speaker: [
          {
            name: "Екатерина Митусова",
            desc: "Лидер WiT Russia, ex-Google, Wrike, коуч ICF",
          },
        ],
        zone: "Barbie",
        section: "Women in tech",
      },
      {
        start: "15:00",
        end: "15:30",
        name: "Личная стратегия для тех, кто устал быть удобным",
        desc: null,
        tag: null,
        speaker: [
          {
            name: "Лидия Рогова",
            desc: "стратег, эксперт по коммуникациям, коуч ICF",
          },
        ],
        zone: "Barbie",
        section: "Women in tech",
      },
      {
        start: "15:30",
        end: "16:00",
        name: "Ментальное расхламление и искусство завершать",
        desc: "Создание карьерных карт и определение вектора развития",
        tag: null,
        speaker: [
          {
            name: "Екатерина Нигай",
            desc: "Product Manager, коуч по нейроинтеграции",
          },
        ],
        zone: "Barbie",
        section: "Women in tech",
      },
      {
        start: "16:00",
        end: "16:30",
        name: "Я в порядке и другие баги",
        desc: "телесная диагностика для IT-специалистов",
        tag: null,
        speaker: [
          { name: "Екатерина Войнова", desc: "Сертифицированный тренер PCM" },
        ],
        zone: "Barbie",
        section: "Women in tech",
      },
      {
        start: "16:30",
        end: "17:50",
        name: "Как агентствам выживать в кризис?",
        desc: null,
        tag: null,
        speaker: null,
        zone: "Barbie",
        section: "Women in tech",
      },
    ],
  },
  {
    zone: "Вегас",
    section: "Project - PM Lunch",
    color: "#f4a261",
    lection: [
      {
        start: "12:00",
        end: "12:50",
        name: "Команда в споре, проект в огне",
        desc: "Инженерный способ выхода из тупика",
        tag: null,
        speaker: [
          {
            name: "Иван Абашкин",
            desc: "Руководитель проектного офиса Радиофид (iRZ)",
          },
        ],
        zone: "Вегас",
        section: "Project - PM Lunch",
      },
      {
        start: "13:00",
        end: "13:50",
        name: "Мастер-класс по p3.express",
        desc: "Здравый смысл в управлении проектами",
        tag: "workshop",
        speaker: [
          {
            name: "Илья Бураев",
            desc: "Руководитель проектов, AI-продукты VK Tech",
          },
        ],
        zone: "Вегас",
        section: "Project - PM Lunch",
      },
      {
        start: "15:00",
        end: "15:50",
        name: 'Деловая игра "Цель проекта"',
        desc: "Как не заблудиться в трёх соснах",
        tag: "game",
        speaker: [{ name: "Алексей Васильев", desc: "Founder BI Pulse" }],
        zone: "Вегас",
        section: "Project - PM Lunch",
      },
      {
        start: "16:00",
        end: "16:50",
        name: "Ты не один в своём аду",
        desc: "Нетворкинг без выгорания",
        tag: null,
        speaker: [
          {
            name: "Ирина Забабонова",
            desc: "Agile Team Leader YADRO, ex PM, ментор и коуч ICF",
          },
        ],
        zone: "Вегас",
        section: "Project - PM Lunch",
      },
      {
        start: "17:00",
        end: "17:50",
        name: "Бизнес-игра по управленческому искусству Self-manage",
        desc: null,
        tag: "game",
        speaker: [
          { name: "Денис Ивченко", desc: "Бизнес-трекер и фасилитатор" },
        ],
        zone: "Вегас",
        section: "Project - PM Lunch",
      },
      {
        start: "19:00",
        end: "23:00",
        name: "Drinkup PM Lunch",
        desc: null,
        tag: "drinkup",
        speaker: null,
        zone: "Вегас",
        section: "Project - PM Lunch",
      },
    ],
  },
  {
    zone: "Дубаи",
    section: "Product+Web3",
    color: "#e9c46a",
    lection: [
      {
        start: "12:00",
        end: "12:50",
        name: "LeanCoffee «Катком по Криптовалютам»",
        desc: null,
        tag: null,
        speaker: [
          {
            name: "Сергей Маслов",
            desc: "фракционный технический директор, криптоевангелист",
          },
        ],
        zone: "Дубаи",
        section: "Product+Web3",
      },
      {
        start: "13:00",
        end: "13:50",
        name: "Постквановая криптография в блокчейне",
        desc: "модель угроз и стратегия миграции",
        tag: null,
        speaker: [
          {
            name: "Алексей Григорьев",
            desc: "Технический Директор RocknBlock",
          },
        ],
        zone: "Дубаи",
        section: "Product+Web3",
      },
      {
        start: "15:00",
        end: "15:50",
        name: "Как свободная крипта становится пролетарием финансовых корпораций",
        desc: null,
        tag: null,
        speaker: [
          {
            name: "Николай Аврамов",
            desc: "Развитие бизнеса EMEA & Americas Aster (Binance-backed)",
          },
        ],
        zone: "Дубаи",
        section: "Product+Web3",
      },
      {
        start: "16:00",
        end: "16:50",
        name: "Карьера как стратегический проект",
        desc: "Воркшоп",
        tag: "workshop",
        speaker: [
          {
            name: "Александр Козуб",
            desc: "CPO в финтехе, ex-Space307, ex-Libertex",
          },
        ],
        zone: "Дубаи",
        section: "Product+Web3",
      },
      {
        start: "17:00",
        end: "17:50",
        name: "Автоматизация рутинных задач в компании через n8n",
        desc: "Воркшоп",
        tag: "workshop",
        speaker: [
          { name: "Антон Баранов", desc: "Product Manager в TrendTech" },
        ],
        zone: "Дубаи",
        section: "Product+Web3",
      },
    ],
  },
  {
    zone: "Тиффани",
    section: "Маркетинг",
    color: "#2a9d8f",
    lection: [
      {
        start: "12:00",
        end: "12:50",
        name: "200 микросервисов, и у каждого свой набор версий инструментов",
        desc: "что мы можем этому противопоставить и причем тут mise",
        tag: null,
        speaker: [
          { name: "Даниил Подольский", desc: "golang евангелист, ЯДРО" },
        ],
        zone: "Тиффани",
        section: "Маркетинг",
      },
      {
        start: "13:00",
        end: "13:50",
        name: "Что было Далее",
        desc: "как упаковать день рождения компании в инфоповод для 7 каналов",
        tag: "workshop",
        speaker: [{ name: "Эльвира Шистерова", desc: "PR Далее" }],
        zone: "Тиффани",
        section: "Маркетинг",
      },
      {
        start: "15:00",
        end: "15:50",
        name: "Кладбище маркетинговых идей",
        desc: "почему 90% не доезжает до прода",
        tag: null,
        speaker: [
          { name: "Константин Хомченко", desc: "Эксперт по маркетингу" },
        ],
        zone: "Тиффани",
        section: "Маркетинг",
      },
      {
        start: "16:00",
        end: "16:50",
        name: "Как получить бюджет на маркетинг",
        desc: "Воркшоп",
        tag: "workshop",
        speaker: [
          {
            name: "Евгения Кюбарсэп",
            desc: "Lead PMM Триколор, экс Циан/Skyeng",
          },
        ],
        zone: "Тиффани",
        section: "Маркетинг",
      },
      {
        start: "17:00",
        end: "17:50",
        name: 'Нытинг: "Почему Лид стоит как самолет?"',
        desc: null,
        tag: null,
        speaker: [
          { name: "Артемий Соколов", desc: "CMO Изоплекс" },
          { name: "Анастасия Волконская", desc: "Руководитель РУССОФТ" },
        ],
        zone: "Тиффани",
        section: "Маркетинг",
      },
      {
        start: "19:00",
        end: "22:00",
        name: "Брейншторм ДАО",
        desc: null,
        tag: null,
        speaker: [{ name: "Дмитрий Мачихин", desc: null }],
        zone: "Тиффани",
        section: "Маркетинг",
      },
    ],
  },
  {
    zone: "Мексика",
    section: "Аналитика+Безопасность",
    color: "#8338ec",
    lection: [
      {
        start: "12:00",
        end: "12:50",
        name: "Стать сильнее ИИ: нейробиология в работе аналитика",
        desc: null,
        tag: null,
        speaker: [
          { name: "Елена Белых", desc: "Руководитель направления в Яндекс" },
        ],
        zone: "Мексика",
        section: "Аналитика+Безопасность",
      },
      {
        start: "13:00",
        end: "13:50",
        name: "Вайбкодинг или архитектура",
        desc: null,
        tag: null,
        speaker: [
          {
            name: "Егор Марюшко",
            desc: "Архитектор решений в школе IISAD/STENET",
          },
        ],
        zone: "Мексика",
        section: "Аналитика+Безопасность",
      },
      {
        start: "15:00",
        end: "15:50",
        name: "Инфобез, требования, моделирование угроз с ИИ",
        desc: null,
        tag: null,
        speaker: [
          {
            name: "Наталья Козлова",
            desc: "Начальник отдела системного анализа в Код безопасности",
          },
        ],
        zone: "Мексика",
        section: "Аналитика+Безопасность",
      },
      {
        start: "16:00",
        end: "16:50",
        name: "Учу взлому ИИ агентов на моковом приложении",
        desc: null,
        tag: null,
        speaker: [
          {
            name: "Александр Князев",
            desc: "Руководитель развития ИИ агентов «АМА»",
          },
        ],
        zone: "Мексика",
        section: "Аналитика+Безопасность",
      },
      {
        start: "17:00",
        end: "17:50",
        name: "Квиз: Проверка зрелости безопасности API",
        desc: null,
        tag: "quiz",
        speaker: [
          {
            name: "Виталий Панасенко",
            desc: "Руководитель разработки продуктов CodeScoring",
          },
        ],
        zone: "Мексика",
        section: "Аналитика+Безопасность",
      },
      {
        start: "19:00",
        end: "22:00",
        name: "Drinkup QA",
        desc: null,
        tag: "drinkup",
        speaker: null,
        zone: "Мексика",
        section: "Аналитика+Безопасность",
      },
    ],
  },
  {
    zone: "Игры Престолов",
    section: "Back",
    color: "#1d3557",
    lection: [
      {
        start: "12:00",
        end: "12:50",
        name: "Куда дошел прогресс в Rust и о чем предпочли не думать?",
        desc: null,
        tag: null,
        speaker: [
          {
            name: "Иван Кривошеев",
            desc: "Руководитель группы разработки Pozitive Technologies",
          },
        ],
        zone: "Игры Престолов",
        section: "Back",
      },
      {
        start: "13:00",
        end: "13:50",
        name: "GTA-сервер на С++ и почему геймплей ушел в JS",
        desc: null,
        tag: null,
        speaker: [{ name: "Даниил Кустов", desc: "C++ Majestic Development" }],
        zone: "Игры Престолов",
        section: "Back",
      },
      {
        start: "15:00",
        end: "15:50",
        name: "Ub — это выдумка",
        desc: null,
        tag: null,
        speaker: [{ name: "Марсель Галимуллин", desc: "C++ Developer Т-Банк" }],
        zone: "Игры Престолов",
        section: "Back",
      },
      {
        start: "16:00",
        end: "16:50",
        name: "Построение ИТ-стратегии развития legacy системы",
        desc: null,
        tag: null,
        speaker: [
          { name: "Ксения Погорельских", desc: "CEO deploy-f.com" },
          { name: "Руслан Сафин", desc: "CTO и партнёр Бындюсофт" },
        ],
        zone: "Игры Престолов",
        section: "Back",
      },
      {
        start: "17:00",
        end: "17:50",
        name: "Паттерны линеаризации операций в распределенных системах",
        desc: null,
        tag: null,
        speaker: [
          {
            name: "Александр Гольдебаев",
            desc: ".NET Developer Золотое Яблоко",
          },
        ],
        zone: "Игры Престолов",
        section: "Back",
      },
      {
        start: "19:00",
        end: "22:00",
        name: "Бункер Golang",
        desc: null,
        tag: null,
        speaker: [{ name: "Петр Растягаев", desc: null }],
        zone: "Игры Престолов",
        section: "Back",
      },
    ],
  },
  {
    zone: "Чикаго",
    section: "QA+Front",
    color: "#06d6a0",
    lection: [
      {
        start: "12:00",
        end: "12:50",
        name: "Миллион строчек нейрослопа: переписать рантайм и не сойти с ума",
        desc: null,
        tag: null,
        speaker: [{ name: "Александр Зайцев", desc: "Node.js X5 Tech" }],
        zone: "Чикаго",
        section: "QA+Front",
      },
      {
        start: "13:00",
        end: "13:50",
        name: "Бросок на адаптацию: как новичку QA не потеряться в подземелье процессов",
        desc: null,
        tag: null,
        speaker: [
          {
            name: "Светлана Филиппова",
            desc: "Старший тестировщик Велесстрой",
          },
          { name: "Елена Шаповалова", desc: "Senior QA" },
        ],
        zone: "Чикаго",
        section: "QA+Front",
      },
      {
        start: "15:00",
        end: "15:50",
        name: "Дуэль за зелёный прогон",
        desc: null,
        tag: null,
        speaker: [{ name: "Алексей Иванов", desc: "QA Engineer в OzonTech" }],
        zone: "Чикаго",
        section: "QA+Front",
      },
      {
        start: "16:00",
        end: "16:50",
        name: "Коллективный разум QA: почему мы все отвечаем одинаково",
        desc: null,
        tag: null,
        speaker: [{ name: "Ксения Иванова", desc: "QA Engineer в Wink" }],
        zone: "Чикаго",
        section: "QA+Front",
      },
      {
        start: "17:00",
        end: "17:50",
        name: "Попробуйте меня переубедить, что React не говно",
        desc: null,
        tag: null,
        speaker: [
          { name: "Алексей Меркушин", desc: "Senior Frontend Developer Linia" },
        ],
        zone: "Чикаго",
        section: "QA+Front",
      },
      {
        start: "19:00",
        end: "22:00",
        name: "Beer JS",
        desc: null,
        tag: "drinkup",
        speaker: null,
        zone: "Чикаго",
        section: "QA+Front",
      },
    ],
  },
  {
    zone: "Friends",
    section: "Management",
    color: "#e76f51",
    lection: [
      {
        start: "12:00",
        end: "12:50",
        name: "Фаундер — не начальник и не подчинённый",
        desc: "Честный разговор для тех, кто устал гадать",
        tag: null,
        speaker: [
          {
            name: "Лидия Рогова",
            desc: "стратег, эксперт по коммуникациям, коуч ICF",
          },
        ],
        zone: "Friends",
        section: "Management",
      },
      {
        start: "13:00",
        end: "13:50",
        name: "Управляемая новизна",
        desc: null,
        tag: null,
        speaker: [
          {
            name: "Александр Садовский",
            desc: "один из создателей Яндекс, победитель «Лидеры России»",
          },
        ],
        zone: "Friends",
        section: "Management",
      },
      {
        start: "15:00",
        end: "15:50",
        name: "Управленческие качели",
        desc: null,
        tag: null,
        speaker: [{ name: "Алексей Пименов", desc: "Founder Neogenda" }],
        zone: "Friends",
        section: "Management",
      },
      {
        start: "16:00",
        end: "16:50",
        name: "SoloFounder vs Product Manager",
        desc: "mindset от хорошего менеджера до предпринимателя",
        tag: null,
        speaker: [
          { name: "Дмитрий Безуглый", desc: "Founder Master-Strategy" },
        ],
        zone: "Friends",
        section: "Management",
      },
      {
        start: "17:00",
        end: "17:50",
        name: "Обзор изменений в мире проектного управления в рамках pmbok 8",
        desc: null,
        tag: null,
        speaker: [
          { name: "Иван Алексеев", desc: "волонтёр отделения PMI PMP, DASSM" },
        ],
        zone: "Friends",
        section: "Management",
      },
    ],
  },
  {
    zone: "Аргентина",
    section: "Hiring",
    color: "#ffb703",
    lection: [
      {
        start: "12:00",
        end: "12:50",
        name: "Интервью: метч, который ищут нанимающие менеджеры",
        desc: null,
        tag: null,
        speaker: [
          { name: "Анна Афонина", desc: "ведущая" },
          {
            name: "Евгения Кадомец",
            desc: "HR Lead ex Яндекс, Домклик, Авито",
          },
        ],
        zone: "Аргентина",
        section: "Hiring",
      },
      {
        start: "13:00",
        end: "13:50",
        name: "Игра: Собери идеальный найм",
        desc: null,
        tag: "game",
        speaker: [{ name: "Анна Афонина", desc: "ведущая" }],
        zone: "Аргентина",
        section: "Hiring",
      },
      {
        start: "15:00",
        end: "15:50",
        name: "Собеседование нанимающего менеджера",
        desc: null,
        tag: null,
        speaker: [
          { name: "Кирилл Мокевнин", desc: "Основатель Hexlet" },
          { name: "Михаил Головатый", desc: "Главный разработчик ДИТ" },
        ],
        zone: "Аргентина",
        section: "Hiring",
      },
      {
        start: "16:00",
        end: "16:50",
        name: "Легитимизация AI на собеседованиях",
        desc: null,
        tag: null,
        speaker: [
          { name: "Антон Черноусов", desc: "Developer advocate Yandex Cloud" },
        ],
        zone: "Аргентина",
        section: "Hiring",
      },
      {
        start: "17:00",
        end: "17:50",
        name: "Стратегия Цифрового Следа",
        desc: "Работа сама тебя найдет или нет",
        tag: null,
        speaker: null,
        zone: "Аргентина",
        section: "Hiring",
      },
    ],
  },
  {
    zone: "Таити",
    section: "Карго-Культ",
    color: "#bc6c25",
    lection: [
      {
        start: "12:00",
        end: "12:50",
        name: "AIAIAIAAAAA…",
        desc: "Открытый микрофон",
        tag: "openmic",
        speaker: [
          {
            name: "Андрей Сухоруков",
            desc: "Team Lead DevOps/SRE/DevSecOps Лаборатории Касперского",
          },
        ],
        zone: "Таити",
        section: "Карго-Культ",
      },
      {
        start: "13:00",
        end: "13:50",
        name: "Сказки софт-скиллов",
        desc: "Открытый микрофон",
        tag: "openmic",
        speaker: [
          {
            name: "Андрей Сухоруков",
            desc: "Team Lead DevOps/SRE/DevSecOps Лаборатории Касперского",
          },
        ],
        zone: "Таити",
        section: "Карго-Культ",
      },
      {
        start: "15:00",
        end: "15:50",
        name: "Гражданин Самозванцев",
        desc: "Открытый микрофон",
        tag: "openmic",
        speaker: [
          {
            name: "Андрей Сухоруков",
            desc: "Team Lead DevOps/SRE/DevSecOps Лаборатории Касперского",
          },
        ],
        zone: "Таити",
        section: "Карго-Культ",
      },
      {
        start: "16:00",
        end: "16:50",
        name: "Успехи у всех и сразу",
        desc: "Открытый микрофон",
        tag: "openmic",
        speaker: [
          {
            name: "Андрей Сухоруков",
            desc: "Team Lead DevOps/SRE/DevSecOps Лаборатории Касперского",
          },
        ],
        zone: "Таити",
        section: "Карго-Культ",
      },
      {
        start: "17:00",
        end: "17:50",
        name: "Метрики",
        desc: "Открытый микрофон",
        tag: "openmic",
        speaker: [
          {
            name: "Андрей Сухоруков",
            desc: "Team Lead DevOps/SRE/DevSecOps Лаборатории Касперского",
          },
        ],
        zone: "Таити",
        section: "Карго-Культ",
      },
    ],
  },
  {
    zone: "Бохо",
    section: "Выход из найма",
    color: "#9b5de5",
    lection: [
      {
        start: "12:00",
        end: "12:50",
        name: "Beyond IT — за границами IT, привычек и очевидного",
        desc: null,
        tag: null,
        speaker: [
          { name: "Роман Уфаев", desc: "Founder Perfect.surf/cnrg.ai" },
          { name: "Юлия Еронен", desc: "Founder Perfect.surf/cnrg.ai" },
        ],
        zone: "Бохо",
        section: "Выход из найма",
      },
      {
        start: "13:00",
        end: "13:50",
        name: "Игра: «Привлеки инвестиции»",
        desc: null,
        tag: "game",
        speaker: [
          { name: "Константин Пантелеев", desc: "партнер kosta.capital" },
          { name: "Виталий Янко", desc: "SPb Founders" },
        ],
        zone: "Бохо",
        section: "Выход из найма",
      },
      {
        start: "15:00",
        end: "16:30",
        name: "Co-Founder Знакомства",
        desc: null,
        tag: "networking",
        speaker: [
          { name: "Владимир Торопецкий", desc: "бизнес-трекер, CPO Моторика" },
        ],
        zone: "Бохо",
        section: "Выход из найма",
      },
      {
        start: "16:30",
        end: "17:50",
        name: "Как перестать застревать на идее",
        desc: null,
        tag: null,
        speaker: [
          {
            name: "Лидия Рогова",
            desc: "стратег, эксперт по коммуникациям, коуч ICF",
          },
        ],
        zone: "Бохо",
        section: "Выход из найма",
      },
    ],
  },
  {
    zone: "Шале",
    section: "Soft Skills Lab",
    color: "#f72585",
    lection: [
      {
        start: "12:00",
        end: "12:50",
        name: "Эмоции на работе — не баг, а фича",
        desc: null,
        tag: null,
        speaker: [
          { name: "Михаил Ромашов", desc: "Product Owner в SberCIB" },
          { name: "Карина Амдиева", desc: "B2B маркетолог, тренер" },
        ],
        zone: "Шале",
        section: "Soft Skills Lab",
      },
      {
        start: "13:00",
        end: "13:50",
        name: "Терпеть нельзя говорить — как поднимать неудобные темы",
        desc: null,
        tag: null,
        speaker: [
          { name: "Михаил Ромашов", desc: "Product Owner в SberCIB" },
          { name: "Карина Амдиева", desc: "B2B маркетолог, тренер" },
        ],
        zone: "Шале",
        section: "Soft Skills Lab",
      },
      {
        start: "15:00",
        end: "15:50",
        name: "Как выйти из режима автопилота",
        desc: "осознанные ответы вместо автоматических звуков",
        tag: null,
        speaker: [
          { name: "Михаил Ромашов", desc: "Product Owner в SberCIB" },
          { name: "Карина Амдиева", desc: "B2B маркетолог, тренер" },
        ],
        zone: "Шале",
        section: "Soft Skills Lab",
      },
      {
        start: "16:00",
        end: "16:50",
        name: "Как быть сволочью в коллективе — прикладное руководство",
        desc: null,
        tag: null,
        speaker: [
          { name: "Михаил Ромашов", desc: "Product Owner в SberCIB" },
          { name: "Карина Амдиева", desc: "B2B маркетолог, тренер" },
        ],
        zone: "Шале",
        section: "Soft Skills Lab",
      },
      {
        start: "17:00",
        end: "17:50",
        name: "ИТ-специалист и методы системного мышления в коммуникации",
        desc: null,
        tag: null,
        speaker: [
          { name: "Михаил Ромашов", desc: "Product Owner в SberCIB" },
          { name: "Карина Амдиева", desc: "B2B маркетолог, тренер" },
        ],
        zone: "Шале",
        section: "Soft Skills Lab",
      },
    ],
  },
  {
    zone: "Ретрорейв",
    section: "Психологи и коучи",
    color: "#b5179e",
    lection: [
      {
        start: "12:00",
        end: "12:50",
        name: "Модели эффективного мышления",
        desc: "как думать точнее, глубже и продуктивнее",
        tag: null,
        speaker: [
          { name: "Евгений Идзиковский", desc: "IT-психолог, бизнес-тренер" },
        ],
        zone: "Ретрорейв",
        section: "Психологи и коучи",
      },
      {
        start: "13:00",
        end: "13:50",
        name: "Как вас видят на самом деле",
        desc: "обратная связь без иллюзий",
        tag: null,
        speaker: [
          { name: "Евгений Идзиковский", desc: "IT-психолог, бизнес-тренер" },
        ],
        zone: "Ретрорейв",
        section: "Психологи и коучи",
      },
      {
        start: "15:00",
        end: "15:50",
        name: "Почему хорошие команды принимают плохие решения",
        desc: null,
        tag: null,
        speaker: [
          { name: "Александра Анисимова", desc: "психолог, бизнес-тренер" },
        ],
        zone: "Ретрорейв",
        section: "Психологи и коучи",
      },
      {
        start: "16:00",
        end: "16:50",
        name: "Зависть в IT",
        desc: null,
        tag: null,
        speaker: [
          { name: "Александра Анисимова", desc: "психолог, бизнес-тренер" },
        ],
        zone: "Ретрорейв",
        section: "Психологи и коучи",
      },
      {
        start: "17:00",
        end: "17:50",
        name: "Я всем должен: вина, граница и страх быть неудобным",
        desc: null,
        tag: null,
        speaker: [
          { name: "Евгений Идзиковский", desc: "IT-психолог, бизнес-тренер" },
        ],
        zone: "Ретрорейв",
        section: "Психологи и коучи",
      },
    ],
  },
  {
    zone: "Стрит-Арт",
    section: "Стрит-Арт",
    color: "#fb8500",
    lection: [
      {
        start: "12:00",
        end: "12:50",
        name: "Вайб-менеджмент: как сохранить энергию в эпоху перегрузки",
        desc: null,
        tag: null,
        speaker: [{ name: "Дарья Мулык", desc: "Сертифицированный коуч ICF" }],
        zone: "Стрит-Арт",
        section: "Стрит-Арт",
      },
      {
        start: "13:00",
        end: "13:50",
        name: "Вы — не баг, вы — фича",
        desc: "где вклад человека незаменим",
        tag: null,
        speaker: [
          {
            name: "Надежда Шипилова",
            desc: "Руководитель проектов, ex-Product BITOBE",
          },
        ],
        zone: "Стрит-Арт",
        section: "Стрит-Арт",
      },
      {
        start: "15:00",
        end: "15:50",
        name: "Как мы мешаем себе развивать карьеру",
        desc: "бинго вредных мыслей",
        tag: null,
        speaker: [
          {
            name: "Варвара Ланцова-Готова",
            desc: "Коуч ICF, психолог, автор подкаста «Карьера сложилась»",
          },
        ],
        zone: "Стрит-Арт",
        section: "Стрит-Арт",
      },
      {
        start: "16:00",
        end: "16:50",
        name: "Как меняется работа руководителя в эпоху AI",
        desc: null,
        tag: null,
        speaker: [
          {
            name: "Ангелина Метсо",
            desc: "Консультант по внедрению AI, ex-VK/Accenture",
          },
        ],
        zone: "Стрит-Арт",
        section: "Стрит-Арт",
      },
      {
        start: "17:00",
        end: "17:50",
        name: "Архетип Айтишника",
        desc: null,
        tag: null,
        speaker: [
          { name: "Анна Забродина-Готова", desc: "Психоаналитик, ex CMO" },
        ],
        zone: "Стрит-Арт",
        section: "Стрит-Арт",
      },
    ],
  },
  {
    zone: "Сеул",
    section: "Дизайн",
    color: "#ff006e",
    lection: [
      {
        start: "12:00",
        end: "12:50",
        name: "Про графдизайн и ИИ",
        desc: null,
        tag: null,
        speaker: [
          {
            name: "Мария Моргунова",
            desc: "Дизайнер Креативная студия Клайбер",
          },
        ],
        zone: "Сеул",
        section: "Дизайн",
      },
      {
        start: "13:00",
        end: "13:50",
        name: "Как раскачивать креативную мышцу",
        desc: null,
        tag: null,
        speaker: [
          {
            name: "Екатерина Кондрашова",
            desc: "Операционный директор Креативная студия Клайбер",
          },
        ],
        zone: "Сеул",
        section: "Дизайн",
      },
      {
        start: "15:00",
        end: "15:50",
        name: "Убейте креатив или спасите проект",
        desc: null,
        tag: null,
        speaker: [
          {
            name: "Пахомова Аврора",
            desc: "Дизайн-лид Диджитал-продакшен ДАЛЕЕ",
          },
        ],
        zone: "Сеул",
        section: "Дизайн",
      },
      {
        start: "16:00",
        end: "17:50",
        name: "Архитектурные Коты",
        desc: "длительная сессия",
        tag: null,
        speaker: [
          {
            name: "Глеб Гончаров",
            desc: "Ведущий технический Архитектор ECOM.TECH",
          },
          { name: "Петр Растегаев", desc: "Software Developer WB" },
          { name: "Никита Бабушкин", desc: "Техлид B2Broker" },
          {
            name: "Елена Федюшкина",
            desc: "Менеджер бизнес-приложений Лемана Про",
          },
        ],
        zone: "Сеул",
        section: "Дизайн",
      },
    ],
  },
  {
    zone: "Ацтеки",
    section: "Vibecode",
    color: "#3a86ff",
    lection: [
      {
        start: "12:00",
        end: "12:50",
        name: "Vibecode сессия «Всё сложно (на самом деле нет)»",
        desc: null,
        tag: null,
        speaker: [
          {
            name: "Александр Ковалёв",
            desc: "Руководитель группы разработки Ozon Tech",
          },
        ],
        zone: "Ацтеки",
        section: "Vibecode",
      },
      {
        start: "13:00",
        end: "13:50",
        name: "Как систематизировать свою работу с роботами",
        desc: null,
        tag: null,
        speaker: [
          {
            name: "Глеб Цыганов",
            desc: "Старший системный аналитик DWH, Яндекс.Такси",
          },
        ],
        zone: "Ацтеки",
        section: "Vibecode",
      },
      {
        start: "15:00",
        end: "15:50",
        name: "CLI команды проекта, удобные для всей команды",
        desc: null,
        tag: null,
        speaker: [{ name: "Дмитрий Буров", desc: "Tech Lead Lamoda" }],
        zone: "Ацтеки",
        section: "Vibecode",
      },
      {
        start: "16:00",
        end: "17:50",
        name: "Архитектурные Коты",
        desc: "длительная сессия",
        tag: null,
        speaker: [
          {
            name: "Глеб Гончаров",
            desc: "Ведущий технический Архитектор ECOM.TECH",
          },
          { name: "Петр Растегаев", desc: "Software Developer WB" },
          { name: "Никита Бабушкин", desc: "Техлид B2Broker" },
          {
            name: "Елена Федюшкина",
            desc: "Менеджер бизнес-приложений Лемана Про",
          },
        ],
        zone: "Ацтеки",
        section: "Vibecode",
      },
    ],
  },
  {
    zone: "Диско",
    section: "Архитектура",
    color: "#8d99ae",
    lection: [
      {
        start: "12:00",
        end: "12:50",
        name: "Архитектурная дискуссия",
        desc: null,
        tag: null,
        speaker: [
          { name: "Петр Растягаев", desc: null },
          { name: "Андрей Порожняков", desc: null },
          { name: "Александр Гольдебаев", desc: null },
        ],
        zone: "Диско",
        section: "Архитектура",
      },
      {
        start: "13:00",
        end: "13:50",
        name: "Мастер-класс по нефункциональным требованиям в Архитектуре",
        desc: null,
        tag: "workshop",
        speaker: [
          { name: "Филипп Дильгядо", desc: null },
          { name: "Даниил Подольский", desc: null },
        ],
        zone: "Диско",
        section: "Архитектура",
      },
      {
        start: "15:00",
        end: "15:50",
        name: "Штанга, смузи и твой первый LLM-бот на LangGraph",
        desc: null,
        tag: null,
        speaker: [
          { name: "Светлана Мелешкина", desc: "Ведущий разработчик НЛМК ИТ" },
        ],
        zone: "Диско",
        section: "Архитектура",
      },
      {
        start: "16:00",
        end: "17:50",
        name: "Архитектурные Коты",
        desc: "длительная сессия",
        tag: null,
        speaker: [
          {
            name: "Глеб Гончаров",
            desc: "Ведущий технический Архитектор ECOM.TECH",
          },
          { name: "Петр Растегаев", desc: "Software Developer WB" },
          { name: "Никита Бабушкин", desc: "Техлид B2Broker" },
          {
            name: "Елена Федюшкина",
            desc: "Менеджер бизнес-приложений Лемана Про",
          },
        ],
        zone: "Диско",
        section: "Архитектура",
      },
    ],
  },
  {
    zone: "Африка",
    section: "Кабинет психолога",
    color: "#7209b7",
    lection: [
      {
        start: "12:00",
        end: "17:50",
        name: "Индивидуальные консультации",
        desc: "весь день",
        tag: null,
        speaker: [
          {
            name: "Дмитрий Меладзе",
            desc: "Психолог, эксперт по эмоциональному интеллекту в IT",
          },
        ],
        zone: "Африка",
        section: "Кабинет психолога",
      },
    ],
  },
];
