export const satSchedule = [
  {
    zone: "Ольга",
    section: "HypeLoad ",
    color: null,
    lection: [
      {
        name: "Начало",
        start: new Date("2024-07-06T11:00:00"),
        end: new Date("2024-07-06T12:00:00"),
        speaker: null,
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Модные Диагнозы",
        start: new Date("2024-07-06T12:00:00"),
        end: new Date("2024-07-06T13:00:00"),
        speaker: [{ name: "Евгений Идзиковский", desc: "IT- Психолог" }],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Как пробить потолок в 500К/месяц",
        start: new Date("2024-07-06T13:00:00"),
        end: new Date("2024-07-06T14:00:00"),
        speaker: [
          { name: "Анна Афонина", desc: "Founder КА HiPoHeads, ProIT Fest" },
          { name: "Анна Атрошкина", desc: "Index Tech        " },
        ],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Личный бренд",
        start: new Date("2024-07-06T14:00:00"),
        end: new Date("2024-07-06T15:00:00"),
        speaker: [
          { name: "Александр Стародубцев", desc: "Frontend Cloud.ru" },
          { name: "Константин Дипеж", desc: "DeusOps" },
        ],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Battle токсиков",
        start: new Date("2024-07-06T15:00:00"),
        end: new Date("2024-07-06T16:00:00"),
        speaker: [
          { name: "Дмитрий Карповский", desc: "основатель HyOO" },
          { name: "Олег Чирухин", desc: "AxiomJDK, Failover Bar" },
          { name: "Александр Токарев", desc: "VP of engineering Xsollaн" },
        ],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "База про доклады. Куда, как и почему не получается",
        start: new Date("2024-07-06T16:00:00"),
        end: new Date("2024-07-06T17:00:00"),
        speaker: [{ name: "Лиза Царева", desc: "Highload" }],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Перерыв",
        start: new Date("2024-07-06T17:00:00"),
        end: new Date("2024-07-06T18:00:00"),
        speaker: null,
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Цифровые экосистемы GitHub и Stackoverflow — возможна ли альтернатива?",
        start: new Date("2024-07-06T18:00:00"),
        end: new Date("2024-07-06T18:30:00"),
        speaker: [{ name: "Егор Бугаенко", desc: "Head of RnD Huawei" }],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Концерт Научно-Технического Репа",
        start: new Date("2024-07-06T18:30:00"),
        end: new Date("2024-07-06T19:30:00"),
        speaker: [{ name: "Влад Горелов", desc: "" }],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
    ],
  },
  {
    zone: "Елена",
    section: "Front ",
    color: null,
    lection: [
      {
        name: "Начало",
        start: new Date("2024-07-06T11:00:00"),
        end: new Date("2024-07-06T12:00:00"),
        speaker: null,
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Круглый стол про использование UI-библиотек",
        start: new Date("2024-07-06T12:00:00"),
        end: new Date("2024-07-06T13:00:00"),
        speaker: [
          { name: "Евгения Полозова", desc: "мейнтейнерка VKUI" },
          { name: "Вадим Аркадов", desc: "Тимлид команды UI-кита Avito" },
          {
            name: "Инна Байкова",
            desc: "техлидка внутреннего UI-кита в Райфайзен-банке",
          },
          { name: "Степан Усов", desc: "тимлид Frontend команды в Nexign" },
          { name: "Дмитрий Карловский", desc: "генеральный дизайнер $mol." },
        ],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Перерыв",
        start: new Date("2024-07-06T13:00:00"),
        end: new Date("2024-07-06T13:30:00"),
        speaker: null,
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Мастер класс по PWA",
        start: new Date("2024-07-06T13:30:00"),
        end: new Date("2024-07-06T14:30:00"),
        speaker: [{ name: "Никита Любицкий", desc: "Team Lead в Звук" }],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Перерыв",
        start: new Date("2024-07-06T14:30:00"),
        end: new Date("2024-07-06T15:00:00"),
        speaker: null,
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Ожидания/реальность во фронтенде",
        start: new Date("2024-07-06T15:00:00"),
        end: new Date("2024-07-06T16:00:00"),
        speaker: [
          {
            name: "Игорь Поляков",
            desc: "Тимлид платформы торгового финансирования. Лидер гильдии Фронтенда Росбанка. \n",
          },
          { name: "Андрей Гостюхин", desc: "Atlantis." },
        ],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Перерыв",
        start: new Date("2024-07-06T16:00:00"),
        end: new Date("2024-07-06T16:30:00"),
        speaker: null,
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Игры от Nexign",
        start: new Date("2024-07-06T16:30:00"),
        end: new Date("2024-07-06T19:30:00"),
        speaker: [
          { name: "Марина Агафонова", desc: "фронтенд-разработчица в Nexign" },
        ],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
    ],
  },
  {
    zone: "",
    section: "Vision ",
    color: null,
    lection: [
      {
        name: "Начало",
        start: new Date("2024-07-06T11:00:00"),
        end: new Date("2024-07-06T12:00:00"),
        speaker: null,
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Как управлять будущим - увидеть неизбежное (Тренды)",
        start: new Date("2024-07-06T12:00:00"),
        end: new Date("2024-07-06T14:00:00"),
        speaker: [
          { name: "Дмитрий Безуглый", desc: "основатель Master Strategy" },
          {
            name: "Михаил Вишневский",
            desc: "лидер функции бизнес-анализа Х5 Технологии",
          },
        ],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Миссия - Что буду делать я (мы). Лидерство.",
        start: new Date("2024-07-06T14:00:00"),
        end: new Date("2024-07-06T16:00:00"),
        speaker: [{ name: "Милитина Фейгина", desc: "CX-researcher" }],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Видение продукта или компании",
        start: new Date("2024-07-06T16:00:00"),
        end: new Date("2024-07-06T19:30:00"),
        speaker: [
          { name: "Максим Яцкевич", desc: "основатель Product Psychology " },
          { name: " AiPartner", desc: null },
        ],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
    ],
  },
  {
    zone: "Елизавета + Екатерина",
    section: "Help ",
    color: null,
    lection: [
      {
        name: "Начало",
        start: new Date("2024-07-06T11:00:00"),
        end: new Date("2024-07-06T12:00:00"),
        speaker: null,
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "12:00 - 12:50 Я этого достоин: как говорить о своих достижениях и получать повышение",
        start: new Date("2024-07-06T12:00:00"),
        end: new Date("2024-07-06T13:00:00"),
        speaker: [
          {
            name: "Ольга Чадулина",
            desc: "Консультант по обучению и развитию в Райффазен банке",
          },
        ],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Перерыв",
        start: new Date("2024-07-06T13:00:00"),
        end: new Date("2024-07-06T13:30:00"),
        speaker: null,
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "13:30 - 14:20 Сам себе проект: как развивать карьеру, чтобы личная юнитка сходилась",
        start: new Date("2024-07-06T13:30:00"),
        end: new Date("2024-07-06T14:30:00"),
        speaker: [
          {
            name: "Елена Соколова",
            desc: "Growth Product менеджер Нетологии, ex-Яндекс Практикум, карьерный консультант IT Digital",
          },
          {
            name: "Лидия Рогова",
            desc: "Групповой и личный коуч ICF, эксперт, ментор, лектор        ",
          },
        ],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Перерыв",
        start: new Date("2024-07-06T14:30:00"),
        end: new Date("2024-07-06T15:00:00"),
        speaker: null,
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "14:50 - 15:40 Я все сказал: управление изменениями и конфликтами в команде",
        start: new Date("2024-07-06T15:00:00"),
        end: new Date("2024-07-06T16:00:00"),
        speaker: [
          {
            name: "Алекей Таушканов",
            desc: "Lead Product Manager Rosstrah.ru",
          },
          { name: "Глеб Юченков", desc: "Product Lead Bonds" },
          { name: "Savings на Московской бирже", desc: null },
        ],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "16:00-17:00 Helpme Хакер найти девушку",
        start: new Date("2024-07-06T16:00:00"),
        end: new Date("2024-07-06T17:00:00"),
        speaker: [
          {
            name: "Алексей Морозов",
            desc: "танцор, певец, пикапер и немножко хакер",
          },
        ],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "17:00 - 17:50 Из крайности в крайность: как выйти из круга переработок и выгорания",
        start: new Date("2024-07-06T17:00:00"),
        end: new Date("2024-07-06T19:30:00"),
        speaker: [{ name: "Евгений Идзиковский", desc: "IT- Психолог" }],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
    ],
  },
  {
    zone: "Петр",
    section: "Oops ",
    color: null,
    lection: [
      {
        name: "Начало",
        start: new Date("2024-07-06T11:00:00"),
        end: new Date("2024-07-06T12:00:00"),
        speaker: null,
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Мы ломали, мы ломали наши пальчики устали",
        start: new Date("2024-07-06T12:00:00"),
        end: new Date("2024-07-06T13:00:00"),
        speaker: [{ name: "Кирилл Борисов", desc: "SRE Lead в MTS Digital" }],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "13:00 - 14:00 Fail versus - В каком бизнесе с инцидентами лучше обращаются",
        start: new Date("2024-07-06T13:00:00"),
        end: new Date("2024-07-06T14:00:00"),
        speaker: null,
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Перерыв",
        start: new Date("2024-07-06T14:00:00"),
        end: new Date("2024-07-06T14:30:00"),
        speaker: null,
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "14:30 - 15:30 Тамада и конкурсы - или как мы делаем выводы, когда кто-то облажался",
        start: new Date("2024-07-06T14:30:00"),
        end: new Date("2024-07-06T15:30:00"),
        speaker: null,
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Перерыв",
        start: new Date("2024-07-06T15:30:00"),
        end: new Date("2024-07-06T16:00:00"),
        speaker: null,
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "16:00 - 16:30 Стендап-сказка на ночь о гитлабе",
        start: new Date("2024-07-06T16:00:00"),
        end: new Date("2024-07-06T16:30:00"),
        speaker: null,
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "16:30 - 17:30 Я видел некое... и готов про него рассказать",
        start: new Date("2024-07-06T16:30:00"),
        end: new Date("2024-07-06T17:00:00"),
        speaker: null,
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "17:30 - 18:00 Открытый микрофон Oops-standup",
        start: new Date("2024-07-06T17:00:00"),
        end: new Date("2024-07-06T19:30:00"),
        speaker: null,
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
    ],
  },
  {
    zone: "Александр",
    section: "Менторинг ",
    color: null,
    lection: [
      {
        name: "Начало",
        start: new Date("2024-07-06T11:00:00"),
        end: new Date("2024-07-06T12:00:00"),
        speaker: null,
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Как и зачем айтишнику начать менторить",
        start: new Date("2024-07-06T12:00:00"),
        end: new Date("2024-07-06T13:00:00"),
        speaker: [
          {
            name: "Катерина Поль",
            desc: "Старший продуктовый, UX/UI дизайнер — Ozon\n",
          },
        ],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Как я портировала приложение на Android, будучи iOS-разрботчиком?",
        start: new Date("2024-07-06T13:00:00"),
        end: new Date("2024-07-06T14:00:00"),
        speaker: [
          {
            name: "Екатерина Батеева",
            desc: "Старший iOS разработчик в компании Додо Инжиниринг",
          },
        ],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Карьерный трек бизнес-аналитика: есть ли жизнь после?",
        start: new Date("2024-07-06T14:00:00"),
        end: new Date("2024-07-06T15:00:00"),
        speaker: [
          { name: "Ольга Мазур", desc: "Product Owner Carsharing - Атом" },
        ],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Чем страшен джун за 30?",
        start: new Date("2024-07-06T15:00:00"),
        end: new Date("2024-07-06T16:00:00"),
        speaker: [{ name: "Илона", desc: "Product Manager         " }],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: " Онбординг: такой разный и такой одинаковый",
        start: new Date("2024-07-06T16:00:00"),
        end: new Date("2024-07-06T17:00:00"),
        speaker: [
          { name: "Андрей Старинин", desc: "Ведущий разработчик — ОМК-ИТ" },
        ],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Менторство как стратегический инструмент тимлида: руководство, развитие команды и улучшение взаимопонимания",
        start: new Date("2024-07-06T17:00:00"),
        end: new Date("2024-07-06T18:00:00"),
        speaker: [
          { name: "Анастасия Золотых", desc: "iOS Platform Team Lead - Звук" },
        ],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Оптимизации методов работы с массивами в JavaScript при слитии массивов",
        start: new Date("2024-07-06T18:00:00"),
        end: new Date("2024-07-06T19:30:00"),
        speaker: [{ name: "Андрей Иванов", desc: "Tech Lead Frontend Axenix" }],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
    ],
  },
  {
    zone: "Ораниенбаум",
    section: "Боль ",
    color: null,
    lection: [
      {
        name: "Начало",
        start: new Date("2024-07-06T11:00:00"),
        end: new Date("2024-07-06T12:00:00"),
        speaker: null,
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Х.х. и в продакшн. (Delivery)",
        start: new Date("2024-07-06T12:00:00"),
        end: new Date("2024-07-06T13:00:00"),
        speaker: [
          { name: "Андрей Громыко", desc: null },
          { name: "Сергей Политыко", desc: null },
          { name: "Дмитрий Тихонов", desc: null },
          { name: "Ганджина Дедюрина", desc: null },
          { name: "Иванов Алексей", desc: null },
          { name: "Константин Волков", desc: null },
          { name: "Юлия Бажанова", desc: null },
        ],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Перерыв",
        start: new Date("2024-07-06T13:00:00"),
        end: new Date("2024-07-06T13:30:00"),
        speaker: null,
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Костыль и Велосипед (Как их избегать)",
        start: new Date("2024-07-06T13:30:00"),
        end: new Date("2024-07-06T14:30:00"),
        speaker: [
          { name: "Софья Каребина", desc: "Head of QA Bimeister" },
          {
            name: "Александр Ковалев",
            desc: "Руководитель группы разработки бизнес логики Product Owner IVA Technologies",
          },
          { name: "Сергей Гаряев", desc: null },
          { name: "Дмитрий Карловский", desc: "основатель HyOO" },
          { name: "Андрей Гостюхин", desc: "Atlantis" },
        ],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Энтерпрайз (Кровавый)",
        start: new Date("2024-07-06T14:30:00"),
        end: new Date("2024-07-06T15:30:00"),
        speaker: [
          {
            name: "Карина Хашина",
            desc: "Руководитель проектов (ex СЕО диджитал студии) Билайн",
          },
          { name: "Алексей Мезенцев", desc: "Директор по продуктам ITPS" },
          {
            name: "Екатерина Борисова",
            desc: "Старший системный аналитик, стрим лид аналитиков Bimeister",
          },
          {
            name: "Илья Черемкин",
            desc: "Директор корпоративного акселератора Корпорация Синергия",
          },
          { name: "Алена Бондарчук", desc: "Бизнес-консультант, ex-COO" },
        ],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Перерыв",
        start: new Date("2024-07-06T15:30:00"),
        end: new Date("2024-07-06T16:00:00"),
        speaker: null,
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Папа может в Си (Когда в разработке уже лет 30)",
        start: new Date("2024-07-06T16:00:00"),
        end: new Date("2024-07-06T17:00:00"),
        speaker: [
          { name: "Вячеслав Ольховченков", desc: null },
          { name: "Сергей Гаряев", desc: null },
          { name: "Алексей Сидоров", desc: null },
          { name: "Ксения Сидорова", desc: null },
          { name: "Александр Ковалев", desc: null },
        ],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "ДедЛайн (Почему мы все до него доводим)",
        start: new Date("2024-07-06T17:00:00"),
        end: new Date("2024-07-06T19:30:00"),
        speaker: [
          { name: "Елена Соколова", desc: null },
          { name: "Лидия Рогова", desc: null },
          { name: "Егор Мыльников", desc: null },
          { name: "Ольга Ермолаева", desc: null },
          { name: "Константин Волков", desc: null },
        ],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
    ],
  },
  {
    zone: "Ресторан Никольский",
    section: "ТОПы ",
    color: null,
    lection: [
      {
        name: "Начало",
        start: new Date("2024-07-06T11:00:00"),
        end: new Date("2024-07-06T15:00:00"),
        speaker: null,
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Сам себе HR BP: как построить крутую команду и добиться выдающихся результатов!",
        start: new Date("2024-07-06T15:00:00"),
        end: new Date("2024-07-06T16:00:00"),
        speaker: [
          {
            name: "Ирина Матвеева",
            desc: "IT HR, IC Agile, Management 3.0, управляющий партнёр Escalate",
          },
          { name: "Юрий Бабак", desc: "СТО платежей Тинькофф" },
          { name: "Максим Чернухин", desc: "СТО СберСтрахование" },
          { name: "Константин Щеглов", desc: "CIO SuperJob" },
        ],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Куда дальше?! или Кого хочу не знаю, кого знаю - не хочу",
        start: new Date("2024-07-06T16:00:00"),
        end: new Date("2024-07-06T17:00:00"),
        speaker: [
          { name: "Виталий Левченко", desc: "Engineering Manager WB" },
          { name: "Александра Рамоненко", desc: "HRD DDL" },
          { name: "Анна Федина", desc: "СТО Альфа-Банк" },
          { name: "Владимир Торопецкий", desc: "CPO Sber AI" },
          { name: "Рената Джордж", desc: null },
        ],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "ТОПовые зарплаты",
        start: new Date("2024-07-06T17:00:00"),
        end: new Date("2024-07-06T19:30:00"),
        speaker: [{ name: "Анна Афонина", desc: "Founder КА HiPoHeads" }],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
    ],
  },
  {
    zone: "Шатер",
    section: "404 ",
    color: null,
    lection: [
      {
        name: "Начало",
        start: new Date("2024-07-06T11:00:00"),
        end: new Date("2024-07-06T12:00:00"),
        speaker: null,
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Android Manual Mobile Test Росбанка",
        start: new Date("2024-07-06T12:00:00"),
        end: new Date("2024-07-06T13:00:00"),
        speaker: [{ name: "Андрей Шевченко", desc: "QA Lead, Росбанк" }],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Мастер класс: Индивидуальный план развития",
        start: new Date("2024-07-06T13:00:00"),
        end: new Date("2024-07-06T14:00:00"),
        speaker: [
          {
            name: "Юрий Дубовой",
            desc: "Руководитель IOS разработки Делимобиль",
          },
        ],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Игра Featureban",
        start: new Date("2024-07-06T14:00:00"),
        end: new Date("2024-07-06T16:00:00"),
        speaker: [{ name: "Алексей Пименов", desc: "Neogenda" }],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: " Баттл Тимлид против HR",
        start: new Date("2024-07-06T16:00:00"),
        end: new Date("2024-07-06T17:00:00"),
        speaker: [
          { name: "Андрей Гостюхин", desc: "Atlantis" },
          { name: "Анна Атрошкина", desc: "Index Tech        " },
        ],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Match meetup",
        start: new Date("2024-07-06T17:00:00"),
        end: new Date("2024-07-06T19:30:00"),
        speaker: [
          { name: "Александра Орова", desc: "Business Project Manager Twinby" },
        ],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
    ],
  },
  {
    zone: "Крыша",
    section: "Network ",
    color: null,
    lection: [
      {
        name: "Начало",
        start: new Date("2024-07-06T11:00:00"),
        end: new Date("2024-07-06T12:30:00"),
        speaker: null,
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Беседа по душам, со спикером",
        start: new Date("2024-07-06T12:30:00"),
        end: new Date("2024-07-06T13:00:00"),
        speaker: [{ name: "Константин Дипеж", desc: "DeusOps" }],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Беседа по душам, со спикером",
        start: new Date("2024-07-06T13:00:00"),
        end: new Date("2024-07-06T13:30:00"),
        speaker: [{ name: "Евгений Идзиковский", desc: "IT- Психолог" }],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Экспертная шляпа",
        start: new Date("2024-07-06T13:30:00"),
        end: new Date("2024-07-06T14:30:00"),
        speaker: [
          {
            name: "Алексей Николаев",
            desc: "руководитель команд b2b продаж it сервисов и продуктов, ex CCO intella.it",
          },
        ],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Идеальные незнакомцы, нетворкинг в игровом формате",
        start: new Date("2024-07-06T14:30:00"),
        end: new Date("2024-07-06T15:30:00"),
        speaker: [
          {
            name: "Александра Орова",
            desc: "Business Project Manager в Twinby",
          },
        ],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Беседа по душам, со спикером",
        start: new Date("2024-07-06T15:30:00"),
        end: new Date("2024-07-06T16:00:00"),
        speaker: [{ name: "Александр Стародубцев", desc: "Frontend Cloud.ru" }],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Беседа по душам, со спикером",
        start: new Date("2024-07-06T16:00:00"),
        end: new Date("2024-07-06T16:30:00"),
        speaker: [{ name: "Егор Бугаенко", desc: "Head of RnD Huawei" }],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "DnD Мастер класс для менеджеров по ретро от Росбанка",
        start: new Date("2024-07-06T16:30:00"),
        end: new Date("2024-07-06T19:30:00"),
        speaker: [
          { name: "Мария Кохановская", desc: "Devrel" },
          { name: "Вячеслав Горбунов", desc: "IT Area Lead" },
          { name: "Андрей Шевченко", desc: "QA Lead" },
          { name: "Петр Брайко", desc: "QA Lead." },
        ],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
    ],
  },
];

export const sunSchedule = [
  {
    zone: "Ольга",
    section: "Management ",
    color: null,
    lection: [
      {
        name: "Начало",
        start: new Date("2024-07-07T11:00:00"),
        end: new Date("2024-07-07T11:00:00"),
        speaker: null,
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Детектор лжи тащи. Тест - часть 1. Ассесмент на несколько навыков менеджера",
        start: new Date("2024-07-07T11:00:00"),
        end: new Date("2024-07-07T11:30:00"),
        speaker: [{ name: "Светлана Скакун", desc: "карьерный коуч" }],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Все мы виноваты в этом пиздеце. Панельная дискуссия о том, с чем столкнулись коллеги, когда стали менеджерами разного уровня",
        start: new Date("2024-07-07T11:30:00"),
        end: new Date("2024-07-07T12:30:00"),
        speaker: [
          { name: "Константин Волков", desc: null },
          { name: "Михаил Трифонов", desc: null },
          { name: "Илья Прахт", desc: null },
          { name: "Александр Ковалев", desc: null },
          { name: "Алексей кузнецов", desc: null },
        ],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Какая разница? Ну, вот, какая разница?! Интервью о смысле получения MBA: зачем, кому, когда и где.",
        start: new Date("2024-07-07T12:30:00"),
        end: new Date("2024-07-07T13:30:00"),
        speaker: null,
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Я сказал, и много что сказал. Не надо мне, пожалуйста, это предъявлять. Профессиональная игра о переговорах.",
        start: new Date("2024-07-07T13:30:00"),
        end: new Date("2024-07-07T14:30:00"),
        speaker: [{ name: "Денис Ивченко", desc: "Школа Переговоров Рызвова" }],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Мне похуй. Я так чувствую и не могу молчать. Практикум по шести методикам обратной связи и неожиданный вывод, к которым они нас приводят",
        start: new Date("2024-07-07T14:30:00"),
        end: new Date("2024-07-07T15:30:00"),
        speaker: [{ name: "Владислав Котов", desc: null }],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Это было не просто смело, это было пиздец как смело. Тест - часть 2. Разбор ответов участников из первой части",
        start: new Date("2024-07-07T15:30:00"),
        end: new Date("2024-07-07T16:00:00"),
        speaker: [{ name: "Светлана Скакун", desc: null }],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Вот, как он может на меня повлиять?. Сессия Мастер Майнда, где можно познакомиться с форматом и решить наболевшее",
        start: new Date("2024-07-07T16:00:00"),
        end: new Date("2024-07-07T17:00:00"),
        speaker: [{ name: "Лидия Рогова", desc: null }],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Я остаюсь с тем, что это был великий сарказм. Игра 100:1 с шуточными и серьезными вопросами про менеджеров. ",
        start: new Date("2024-07-07T17:00:00"),
        end: new Date("2024-07-07T19:30:00"),
        speaker: null,
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
    ],
  },
  {
    zone: "Николай",
    section: "StartUp ",
    color: null,
    lection: [
      {
        name: "Начало",
        start: new Date("2024-07-07T11:00:00"),
        end: new Date("2024-07-07T12:00:00"),
        speaker: null,
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Несите свои pet-projects! (Мастермайнд для основателей)",
        start: new Date("2024-07-07T12:00:00"),
        end: new Date("2024-07-07T12:30:00"),
        speaker: [
          { name: "Виталий Янко", desc: null },
          { name: "Вячеслав Дерновский", desc: null },
          { name: "Анна Афонина", desc: null },
          { name: "Галина Лихицкая", desc: null },
          { name: "Кирилл Непомилуев ", desc: null },
        ],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Sales points стартапов для найма команды (Мастер-класс)",
        start: new Date("2024-07-07T12:30:00"),
        end: new Date("2024-07-07T13:00:00"),
        speaker: [{ name: "Анна Афонина", desc: null }],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "AI всемогущий и ТОП 20 ошибок серийных предпринимателей (Мастер-класс)",
        start: new Date("2024-07-07T13:00:00"),
        end: new Date("2024-07-07T13:30:00"),
        speaker: [{ name: "Галина Лихицкая", desc: null }],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Что мешает вам денег заработать?(Кейсы)",
        start: new Date("2024-07-07T13:30:00"),
        end: new Date("2024-07-07T14:00:00"),
        speaker: [
          { name: "Виталий Янко", desc: null },
          { name: "Вячеслав Дерновский", desc: null },
          { name: "Галина Лихицкая", desc: null },
        ],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Комплект основателя: как собраться под инвестиции через выбор рынка, продажи и правильную беседу с инвесторами (Мастер-класс)",
        start: new Date("2024-07-07T14:00:00"),
        end: new Date("2024-07-07T15:00:00"),
        speaker: [
          { name: "Виталий Янко", desc: null },
          { name: "Вячеслав Дерновский", desc: null },
          { name: "Тимур Венецианов", desc: null },
          { name: "Илья Черёмкин", desc: null },
        ],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "“Экипаж на IPO” от команды Brainbox.vc (Игра-симулятор)",
        start: new Date("2024-07-07T15:00:00"),
        end: new Date("2024-07-07T16:30:00"),
        speaker: [{ name: "Альберт Алиев", desc: null }],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Нетворк",
        start: new Date("2024-07-07T16:30:00"),
        end: new Date("2024-07-07T17:00:00"),
        speaker: null,
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Crash Test: 5 питчей стартапов и разбор от инвесторов",
        start: new Date("2024-07-07T17:00:00"),
        end: new Date("2024-07-07T19:30:00"),
        speaker: [
          { name: "Виталий Янко", desc: null },
          { name: "Константин Пантелеев", desc: null },
          { name: "Игорь Мощук", desc: null },
          { name: "Вячеслав Дерновский", desc: null },
          { name: "Рената Джордж", desc: null },
          { name: "Илья Черёмкин", desc: null },
          { name: "Альбет Алиев ", desc: null },
        ],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
    ],
  },
  {
    zone: "Зал Романовы",
    section: "HR ",
    color: null,
    lection: [
      {
        name: "Начало",
        start: new Date("2024-07-07T11:00:00"),
        end: new Date("2024-07-07T12:00:00"),
        speaker: null,
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "World cafe. «Эй, HR! разовьем потенциал?» говорим о наставничестве, менторинге, коучинге, баддинге и сообществах",
        start: new Date("2024-07-07T12:00:00"),
        end: new Date("2024-07-07T13:00:00"),
        speaker: [
          { name: "Юлия Саландаева", desc: null },
          { name: "Константин Дипеж", desc: null },
          { name: "Влад Котов", desc: null },
          { name: "Антон Волков", desc: null },
          { name: "Лера Ширяева", desc: null },
          { name: "Анна Голикова", desc: null },
          { name: "Мария Курякова", desc: null },
          { name: "Ольга Станцель", desc: null },
          { name: "Алена Новоселова", desc: null },
          { name: "Ирина Матвеева", desc: null },
          { name: "Ольга Власова", desc: null },
          { name: "Никита Мошкалов", desc: null },
        ],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "игра Perfect Match. Каждый IT-шник желает знать, где ему работать.6 типов компаний; 6 цветов спиральной динамики - примерь!",
        start: new Date("2024-07-07T13:00:00"),
        end: new Date("2024-07-07T14:30:00"),
        speaker: [
          { name: "Мария Курякова", desc: null },
          { name: "Ирина Матвеева", desc: null },
          { name: "Анна Афонина", desc: null },
          { name: "Мария Константиниди", desc: null },
          { name: "Евгений Югай", desc: null },
          { name: "Алена Новоселова", desc: null },
          { name: "Юлия Вокуева", desc: null },
          { name: "Ксения Буренина", desc: null },
        ],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "перерыв",
        start: new Date("2024-07-07T14:30:00"),
        end: new Date("2024-07-07T15:00:00"),
        speaker: null,
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Воркшоп Самоходная команда через оптику Management 3.0для HR, лидов, менеджеров и тех, кого просто достало пинать коллег",
        start: new Date("2024-07-07T15:00:00"),
        end: new Date("2024-07-07T16:30:00"),
        speaker: [
          { name: "Ирина Матвеева", desc: null },
          { name: "Ксения Буренина", desc: null },
          { name: "Юлия Вокуева", desc: null },
          { name: "Ирина Веревка", desc: null },
          { name: "Ася Маркеви", desc: null },
          { name: "Анна Голикова", desc: null },
        ],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "перерыв",
        start: new Date("2024-07-07T16:30:00"),
        end: new Date("2024-07-07T17:00:00"),
        speaker: null,
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Круглый стол.Кайфовать нельзя работать: как делать дело, когда хочется комфорта",
        start: new Date("2024-07-07T17:00:00"),
        end: new Date("2024-07-07T19:30:00"),
        speaker: [
          { name: "Алла Гузова", desc: null },
          { name: "Ирина Матвеева", desc: null },
          { name: "Мария Константиниди", desc: null },
          { name: "Евгений Югай", desc: null },
          { name: "Андрей Гостюхин", desc: null },
          { name: "Мария Курякова", desc: null },
          { name: "Ася Маркевич", desc: null },
        ],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
    ],
  },
  {
    zone: "Петр",
    section: "Аналитика ",
    color: null,
    lection: [
      {
        name: "Начало",
        start: new Date("2024-07-07T11:00:00"),
        end: new Date("2024-07-07T12:00:00"),
        speaker: null,
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Фокус на данные, а не исследования (мозговой-шурм)",
        start: new Date("2024-07-07T12:00:00"),
        end: new Date("2024-07-07T13:00:00"),
        speaker: [{ name: "Ирина Ильюшко", desc: "Руководитель проектов " }],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Преимущества использования OpenAPI для системного дизайна(мастер-класс)",
        start: new Date("2024-07-07T13:00:00"),
        end: new Date("2024-07-07T13:30:00"),
        speaker: [{ name: "Елизавета Акманова", desc: null }],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Перерыв",
        start: new Date("2024-07-07T13:30:00"),
        end: new Date("2024-07-07T14:00:00"),
        speaker: null,
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Почему рефакторинг документации так важен для успешного продукта (игра)",
        start: new Date("2024-07-07T14:00:00"),
        end: new Date("2024-07-07T15:00:00"),
        speaker: [
          {
            name: "Долгина Татьяна",
            desc: "Ведущий системный аналитик, IT_One ",
          },
        ],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Перерыв",
        start: new Date("2024-07-07T15:00:00"),
        end: new Date("2024-07-07T15:30:00"),
        speaker: null,
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Код и архитектура: шаги по улучшению масштабируемости и качества(Мастер-класс)",
        start: new Date("2024-07-07T15:30:00"),
        end: new Date("2024-07-07T16:00:00"),
        speaker: [
          { name: "Абдуллин Булат", desc: "Tech, Team Lead. ИнфоТеКС " },
        ],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Мотивация: больше, не значит лучше.(доклад)",
        start: new Date("2024-07-07T16:00:00"),
        end: new Date("2024-07-07T16:30:00"),
        speaker: [
          {
            name: "Наталья Гусева",
            desc: "старший системный аналитик ecom.tech ",
          },
        ],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Как микроэвентами облегчаем процессинг, хранение и обратную совместимость. На пальцах (мастер-класс)",
        start: new Date("2024-07-07T16:30:00"),
        end: new Date("2024-07-07T17:00:00"),
        speaker: [
          {
            name: "Прохоров Николай",
            desc: "Ведущий системный аналитик, Звук ",
          },
        ],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Что, где, когда (игра)",
        start: new Date("2024-07-07T17:00:00"),
        end: new Date("2024-07-07T19:30:00"),
        speaker: [{ name: "Анна Горбатенко", desc: null }],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
    ],
  },
  {
    zone: "Александр",
    section: "Try ",
    color: null,
    lection: [
      {
        name: "Начало",
        start: new Date("2024-07-07T11:00:00"),
        end: new Date("2024-07-07T12:00:00"),
        speaker: null,
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Try UX Исследование",
        start: new Date("2024-07-07T12:00:00"),
        end: new Date("2024-07-07T13:30:00"),
        speaker: [
          { name: "Анна Котельникова", desc: "UX researcher La Tech  " },
        ],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Перерыв",
        start: new Date("2024-07-07T13:30:00"),
        end: new Date("2024-07-07T14:00:00"),
        speaker: null,
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Try SRE",
        start: new Date("2024-07-07T14:00:00"),
        end: new Date("2024-07-07T15:00:00"),
        speaker: [
          {
            name: "Дмитрий Синявский",
            desc: "SRE Vitech, Виктория Волкова, SRE  Tinkoff ",
          },
        ],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Игра Try Data Engineering",
        start: new Date("2024-07-07T15:00:00"),
        end: new Date("2024-07-07T16:00:00"),
        speaker: [{ name: "Полина Рейнер", desc: "Data Engineer, Axel PRO" }],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Try ML распознавание Дипфейков",
        start: new Date("2024-07-07T16:00:00"),
        end: new Date("2024-07-07T17:00:00"),
        speaker: [
          { name: "Роговой Виталий", desc: "CTO DetAFake" },
          { name: "Артур Сапрыкин", desc: "datamagic" },
        ],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Try: 6 реальных историй из мира QA",
        start: new Date("2024-07-07T17:00:00"),
        end: new Date("2024-07-07T19:30:00"),
        speaker: [
          {
            name: "Бровко Андрей",
            desc: "Руководитель тестирования Авито Авто",
          },
        ],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
    ],
  },
  {
    zone: "Ораниенбаум",
    section: "БДСМ ",
    color: null,
    lection: [
      {
        name: "Начало",
        start: new Date("2024-07-07T11:00:00"),
        end: new Date("2024-07-07T12:00:00"),
        speaker: null,
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "практическая работа по нетворкингу",
        start: new Date("2024-07-07T12:00:00"),
        end: new Date("2024-07-07T13:00:00"),
        speaker: null,
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "с чего начать PR",
        start: new Date("2024-07-07T13:00:00"),
        end: new Date("2024-07-07T14:00:00"),
        speaker: null,
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "панельная дискуссия увас точно есть деньги на нового клиента? сколько стоит пресейл",
        start: new Date("2024-07-07T14:00:00"),
        end: new Date("2024-07-07T15:30:00"),
        speaker: null,
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "GenAI - Как изменится продакшен будущего, и почему NFT может вернуться в игру",
        start: new Date("2024-07-07T15:30:00"),
        end: new Date("2024-07-07T17:00:00"),
        speaker: null,
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Развитие силами команды / ???",
        start: new Date("2024-07-07T17:00:00"),
        end: new Date("2024-07-07T19:30:00"),
        speaker: null,
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
    ],
  },
  {
    zone: "Крыша",
    section: "Network ",
    color: null,
    lection: [
      {
        name: "Начало",
        start: new Date("2024-07-07T11:00:00"),
        end: new Date("2024-07-07T13:00:00"),
        speaker: null,
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Нетворкинг в стиле ’Поговорим о разном’",
        start: new Date("2024-07-07T13:00:00"),
        end: new Date("2024-07-07T15:00:00"),
        speaker: [
          {
            name: "Александра Орова",
            desc: "Business Project Manager в Twinby",
          },
        ],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Карьерная шляпа",
        start: new Date("2024-07-07T15:00:00"),
        end: new Date("2024-07-07T16:00:00"),
        speaker: [
          {
            name: "Елена Соколова",
            desc: "Growth Product менеджер Нетологии, ex-Яндекс Практикум, карьерный консультант IT Digital",
          },
        ],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Speed one-to-one. Деврел Рекрутеры",
        start: new Date("2024-07-07T16:00:00"),
        end: new Date("2024-07-07T19:30:00"),
        speaker: [
          { name: "Адель Макашева", desc: "Fullstack Devrel в Cloud.ru" },
          {
            name: "Марина Ломадзе",
            desc: "Head of Talent Acquisition в Cloud.ru",
          },
        ],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
    ],
  },
  {
    zone: "Шатер",
    section: "404 ",
    color: null,
    lection: [
      {
        name: "Начало",
        start: new Date("2024-07-07T11:00:00"),
        end: new Date("2024-07-07T12:00:00"),
        speaker: null,
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Реализация Видения Vision",
        start: new Date("2024-07-07T12:00:00"),
        end: new Date("2024-07-07T13:00:00"),
        speaker: [{ name: "Владимир Торопецкий", desc: "CPO Sber AI" }],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "DevRel Круглый стол: У семи Деврел дитя без пиара...Как перестать быть нянькой в компании",
        start: new Date("2024-07-07T13:00:00"),
        end: new Date("2024-07-07T14:30:00"),
        speaker: [
          {
            name: "Алексей Мерсон",
            desc: "Developer Advocate в Sage (Т-Банк)",
          },
          { name: "Александр Фатин", desc: "DevRel PostgreSQL" },
          {
            name: "Роман Поборчий",
            desc: "Консультант по выступлениям на профессиональные темы",
          },
          {
            name: "Антон Черноусов",
            desc: "Developer advocate в Yandex Cloud",
          },
          {
            name: "Наталья Петухова",
            desc: "Ведущий менеджер по работе с партнерами, Стачка",
          },
          { name: "Елизавета Царева", desc: "Программный координатор, Онтико" },
        ],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "404 Reroute: как сменить роль в IT и найти свой путь",
        start: new Date("2024-07-07T14:30:00"),
        end: new Date("2024-07-07T16:00:00"),
        speaker: [
          { name: "Алена Бондарчук", desc: "Бизнес-консультант, ex-COO" },
        ],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "System Design мок интервью",
        start: new Date("2024-07-07T16:00:00"),
        end: new Date("2024-07-07T17:00:00"),
        speaker: [
          {
            name: "Невзоров Владимир",
            desc: "Старший Back разработчик Servicepipe",
          },
        ],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Аукцион Травм. Игра",
        start: new Date("2024-07-07T17:00:00"),
        end: new Date("2024-07-07T19:30:00"),
        speaker: [
          { name: "Евгений Идзиковский", desc: null },
          { name: "Саша Анисимова", desc: "IT психолог. " },
        ],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
    ],
  },
  {
    zone: "Ресторан +СПА",
    section: "Стачка DevRel ",
    color: null,
    lection: [
      {
        name: "Начало",
        start: new Date("2024-07-07T11:00:00"),
        end: new Date("2024-07-07T15:00:00"),
        speaker: null,
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Мастермайнд-брейк для DevRel-специалистовОбсудим текущие сложные кейсы, проблемы и задачиПоделимся опытом и поможем друг другу за чашечкой кофе(Ресторан)Участвуют все желающие по предварительной записи (10 мест)",
        start: new Date("2024-07-07T15:00:00"),
        end: new Date("2024-07-07T17:00:00"),
        speaker: null,
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
      {
        name: "Как не запаритьсяКак спасти себя в круговороте деврельского достигаторства и командировок(Аромасауна в СПА)",
        start: new Date("2024-07-07T17:00:00"),
        end: new Date("2024-07-07T19:30:00"),
        speaker: [
          { name: "Адель Макашева", desc: "Fullstack Devrel в Cloud.ru\n" },
        ],
        desc: null,
        tag: null,
        zone: "Зал Романовы",
        section: "HR ",
      },
    ],
  },
];
